version: '3.5'

services:
  postgres:
    container_name: SpendingTracker
    image: postgres
    environment:
      POSTGRES_USER: stadmin
      POSTGRES_PASSWORD: stadmin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
